# -*- coding: utf-8 -*-
"""chroma_db_evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMoKezZ0kcu6qFfhLqKPr8MEZG5D4zLs
"""

from chunking_evaluation.chunking import FixedTokenChunker, RecursiveTokenChunker, ClusterSemanticChunker, LLMSemanticChunker, KamradtModifiedChunker
from chunking_evaluation import GeneralEvaluation
from chunking_evaluation.utils import openai_token_count
from sentence_transformers import SentenceTransformer
from typing import List
import pandas as pd
from chromadb import Documents, EmbeddingFunction, Embeddings

import chromadb.api.client
original_delete_collection = chromadb.api.client.Client.delete_collection

def patched_delete_collection(self, name, **kwargs):
    try:
        return original_delete_collection(self, name, **kwargs)
    except chromadb.errors.NotFoundError:
        print("Collection does not exist, creating it...")
        # Collection doesn't exist, which is fine - we'll create it
        pass

chromadb.api.client.Client.delete_collection = patched_delete_collection

MODEL_NAME = "all-MiniLM-L6-v2"
TRAINED_MODEL_PATH = "models/best_model"

class SentenceTransformerEF(EmbeddingFunction):

    def __init__(self, model_name: str = MODEL_NAME):
        self.model_name = model_name
        self.model = SentenceTransformer(model_name)
    def __call__(self, input: Documents) -> Embeddings:

        embeddings = self.model.encode(
            input,
            convert_to_tensor=False,
            show_progress_bar=False
        ).tolist()
        return embeddings

trained_ef = SentenceTransformerEF(TRAINED_MODEL_PATH)
ef = SentenceTransformerEF(MODEL_NAME)

chunkers = [
    ClusterSemanticChunker(embedding_function=ef, max_chunk_size=400),
    ClusterSemanticChunker(embedding_function=ef, max_chunk_size=200),
    KamradtModifiedChunker(avg_chunk_size = 400, embedding_function = ef),
    ClusterSemanticChunker(embedding_function=trained_ef, max_chunk_size=400),
    ClusterSemanticChunker(embedding_function=trained_ef, max_chunk_size=200),
    KamradtModifiedChunker(avg_chunk_size = 400, embedding_function = trained_ef),

    # RecursiveTokenChunker(chunk_size=800, chunk_overlap=400, length_function=openai_token_count),
    # FixedTokenChunker(chunk_size=800, chunk_overlap=400, encoding_name="cl100k_base"),
    # RecursiveTokenChunker(chunk_size=400, chunk_overlap=200, length_function=openai_token_count),
    # FixedTokenChunker(chunk_size=400, chunk_overlap=200, encoding_name="cl100k_base"),
    # RecursiveTokenChunker(chunk_size=400, chunk_overlap=0, length_function=trained_ef),
    # FixedTokenChunker(chunk_size=400, chunk_overlap=0, encoding_name="cl100k_base"),
    # RecursiveTokenChunker(chunk_size=200, chunk_overlap=0, length_function=openai_token_count),
    # FixedTokenChunker(chunk_size=200, chunk_overlap=0, encoding_name="cl100k_base"),

]

evaluation = GeneralEvaluation()

results = []

df = pd.DataFrame()


for i, chunker in enumerate(chunkers):
    print(f"Evaluating chunker {i+1} of {len(chunkers)}")
    result = evaluation.run(chunker, ef, retrieve=5)
    del result['corpora_scores']  # Remove detailed scores for brevity
    chunk_size = chunker._chunk_size if hasattr(chunker, '_chunk_size') else 0
    chunk_overlap = chunker._chunk_overlap if hasattr(chunker, '_chunk_overlap') else 0
    model_name = ""
    if hasattr(chunker, 'embedding_function'):
        model_name = chunker.embedding_function.model_name
    result['chunker'] = chunker.__class__.__name__ + f"{model_name}_{chunk_size}_{chunk_overlap}"
    results.append(result)

    # Update the DataFrame
    df = pd.DataFrame(results)

df.to_csv('results/chroma_db_evaluate/chunking_results_extra.csv', index=False)